id: detonate_url_-_crowdstrike
version: -1
name: Detonate URL - CrowdStrike
fromversion: 4.0.0
description: Detonate one or more files using the CrowdStrike Falcon Sandbox integration. This playbook
  returns relevant reports to the War Room and file reputations to the context data.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 668e67e6-73cd-4e7c-85a8-46255c955974
    type: start
    task:
      id: 668e67e6-73cd-4e7c-85a8-46255c955974
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 6403715f-7609-482d-8e3b-f3451deec657
    type: condition
    task:
      id: 6403715f-7609-482d-8e3b-f3451deec657
      version: -1
      name: Is CrowdStrike enabled?
      description: |
        Verify that there is a valid instance of CrowdStrike enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: VxStream
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 2b8ce551-18fb-4e27-8e6f-4163cab0b982
    type: title
    task:
      id: 2b8ce551-18fb-4e27-8e6f-4163cab0b982
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: fd07a683-fa7f-437c-871d-a7feaeb12433
    type: regular
    task:
      id: fd07a683-fa7f-437c-871d-a7feaeb12433
      version: -1
      name: CrowdStrike Scan
      description: Download the pdf report to the War Room.
      script: VxStream|||crowdstrike-scan
      type: regular
      iscommand: true
      brand: VxStream
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      file:
        complex:
          root: File
          accessor: SHA256
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: f1a0b08b-2fde-4717-8271-a0556e57f462
    type: regular
    task:
      id: f1a0b08b-2fde-4717-8271-a0556e57f462
      version: -1
      name: CrowdStrike Upload Sample
      description: Upload samle to crowdstrike.
      script: VxStream|||crowdstrike-submit-url
      type: regular
      iscommand: true
      brand: VxStream
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      dontThrowErrorOnFileDetonation:
        simple: "true"
      environmentID:
        complex:
          root: inputs.EnvironmentID
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 4dbb3f3c-80d3-424f-87b0-17ea9a7ee90a
    type: condition
    task:
      id: 4dbb3f3c-80d3-424f-87b0-17ea9a7ee90a
      version: -1
      name: Is there a URL to detonate?
      description: Checks whether there's a file to detonate.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.URL
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 0e53c54d-ec59-4b75-837d-dcba76b5c35d
    type: playbook
    task:
      id: 0e53c54d-ec59-4b75-837d-dcba76b5c35d
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        complex:
          root: File
          accessor: SHA256
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: file
      PollingCommandName:
        simple: crowdstrike-scan
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: File(val.state === 'NO_CONTENT').hash
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 063f8872-26bf-4bf9-8caa-645a82166659
    type: condition
    task:
      id: 063f8872-26bf-4bf9-8caa-645a82166659
      version: -1
      name: Is url detonated?
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: CrowdStrike
                accessor: JobID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 275,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 605,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: URL
  value:
    complex:
      root: URL
      accessor: Data
  required: false
  description: URL to detonate.
  playbookInputQuery: null
- key: EnvironmentID
  value:
    simple: "100"
  required: false
  description: Environment ID to submit the file to. To get all IDs run the crowdstrike-get-environments
    command.
  playbookInputQuery: null
- key: Interval
  value:
    simple: "5"
  required: false
  description: Polling frequency - how often the polling command should run (minutes)
  playbookInputQuery: null
- key: Timeout
  value:
    simple: "30"
  required: false
  description: How much time to wait before a timeout occurs  (minutes)
  playbookInputQuery: null
outputs:
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: File.Malicious
  description: The File malicious description
  type: unknown
- contextPath: File.Type
  description: File type e.g. "PE"
  type: string
- contextPath: File.Size
  description: File size
  type: number
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: File.Name
  description: Filename
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File
  description: The File object
  type: unknown
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: DBotScore
  description: The DBotScore object
  type: unknown
- contextPath: DBotScore.Indicator
  description: The indicator we tested
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
tests:
  - Test-Detonate URL - Crowdstrike
