version: 2.1
jobs:
  Level1-1:
    docker:
      - image: devdemisto/content-build:3.0.0.7332
    steps:
      - run:
          name: level1-1-step1
          shell: /bin/bash
          command: |
            exit 0
          when: always
  Level1-2:
    docker:
      - image: devdemisto/content-build:3.0.0.7332
    steps:
      - run:
          name: level1-2-step1
          shell: /bin/bash
          command: |
            echo "running level1-2-step1"
            exit 1
          when: always
      - run:
          name: level1-2-step2
          shell: /bin/bash
          command: |
            echo "running level1-2-step2"
            exit 0
      - run:
          name: level1-2-step3
          shell: /bin/bash
          command: |
            echo "running level1-2-step3"
            echo "should run even when a previous step failed"
            exit 0
          when: on_fail
  Level2-1:
    docker:
      - image: devdemisto/content-build:3.0.0.7332
    steps:
      - run:
          name: level2-1-step1
          shell: /bin/bash
          command: |
            exit 0
          when: always


workflows:
  version: 2
  commit:
    jobs:
      - Level1-1
      - Level1-2
      - Level2-1:
          requires:
            - Level1-1
            - Level1-2
