version: 2.1
jobs:
  Level1-1:
    docker:
      - image: devdemisto/content-build:3.0.0.7332
    steps:
      - run:
          name: level1-1-step1
          shell: /bin/bash
          command: |
            exit 0
          when: always
  Level2-1:
    docker:
      - image: devdemisto/content-build:3.0.0.7332
      steps:
        - run:
            name: level2-1-step1
            shell: /bin/bash
            command: |
              exit 0
            when: always


workflows:
  version: 2
  commit:
    jobs:
      - Level1-1
      - Level2-1:
          requires:
            - Level1-1